---

- name: Install docker server and initialize
  gather_facts: false
  hosts: localhost
  tasks:
    - name: Ensure that sudo is installed.
      apk:
        name: sudo
        state: present
    - name: Docker install
      become: true
      apk:
        name: docker
        state: present
    - name: Add user to Docker group
      local_action: command addgroup jenkins docker
    - name: Add Docker service start at boot
      local_action: command rc-update add docker boot
    - name: Start Docker service
      local_action: command service docker start

    - name: Display the User name
      ansible.builtin.debug:
        msg: "Hello Ansible User {{ username_on_the_host.stdout }} from Jenkins and Ansible!!"

