---
    - name: Install docker
      include: docker.yml
    - name: Pull nginx image
      docker_container:
        name: balancer
        state: started
        image: "nginx:alpine"
        pull: true
        ports:
          - "5000:5000" 
