---
- name: Pull webapp image and run
  gather_facts: false
  hosts: build_host
  become: true
  tasks:
  - name: Run webapp_1
    docker_container:
      name: webapp_1
      networks:
      - name: "webapp"     
      state: started
      image: "quebramadeira/examapp"
      pull: true
      ports:
      - "5000:5000"
  - name: Run webapp_2
    docker_container:
      name: webapp_2
      networks:
      - name: "webapp"     
      state: started
      image: "quebramadeira/examapp"
      pull: true
      ports:
      - "5001:5000" 
  - name: Run webapp_3
    docker_container:
      name: webapp_3
      networks:
      - name: "webapp"     
      state: started
      image: "quebramadeira/examapp"
      pull: true
      ports:
      - "5002:5000" 
