---
- name: Pull nginx image and run
  gather_facts: false
  hosts: build_host
  become: true
  tasks:
  
  - name: Include variables.
    include_vars: "main.yml"
  - name: Define nginx_user.
    set_fact:
      nginx_user: "{{ __nginx_user }}"
    when: nginx_user is not defined
    
  - name: Run balancer
    docker_container:
      name: balancer
      networks:
      - name: "webapp"
      volumes: /home/jenkins/nginx:/etc/nginx
      state: started
      image: "nginx:alpine"
      pull: true
      ports:
      - "8081:80"
      
  - name: Copy nginx configuration in place.
    template:
      src: "{{ nginx_conf_template }}"
      dest: "{{ nginx_conf_file_path }}"
      owner: root
      group: "{{ root_group }}"
      mode: 0644
    notify:
      - reload nginx

  - name: Ensure nginx service is running as configured.
    service:
      name: nginx
      state: "{{ nginx_service_state }}"
      enabled: "{{ nginx_service_enabled }}"
